apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: bitwardensecret-homepage
  namespace: homepage
  labels:
      app.kubernetes.io/name: bitwardensecret
      app.kubernetes.io/instance: bitwardensecret-homepage
      app.kubernetes.io/part-of: sm-operator
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/created-by: sm-operator
spec:
  organizationId: "577e1b7a-7f02-46a9-8af6-b31301796aa2"
  secretName: bw-homepage-secret
  onlyMappedSecrets: true # default is true
  map:
      - bwSecretId: cf2bf83f-1e14-4c43-90fb-5d0eee906dac
        secretKeyName: HOMEPAGE_ALLOWED_HOSTS
      - bwSecretId: 6ce28b5e-8f48-485f-8814-a6a6ca376b41
        secretKeyName: HOMEPAGE_VAR_FROSTMOURNE_URL
      - bwSecretId: dedc9e88-e508-4964-9dfc-ced92fefda45
        secretKeyName: HOMEPAGE_VAR_FROSTMOURNE_USER
      - bwSecretId: 9ce86548-012e-4e29-b7b4-f5cbd601fd59
        secretKeyName: HOMEPAGE_VAR_FROSTMOURNE_APIKEY
      - bwSecretId: b290b8fb-8d62-45c7-b744-5b240285aece
        secretKeyName: HOMEPAGE_VAR_SHALAMAYNE_URL
      - bwSecretId: eca7279a-9ad2-43ae-8cf4-d983bf39431e
        secretKeyName: HOMEPAGE_VAR_SHALAMAYNE_USER
      - bwSecretId: 1ebf8b34-3c4e-4b5f-8a36-73d17bd38782
        secretKeyName: HOMEPAGE_VAR_SHALAMAYNE_APIKEY
      - bwSecretId: a51ca55f-920b-461a-9f76-2a3d21e231f9
        secretKeyName: HOMEPAGE_VAR_UNIFI_USER
      - bwSecretId: ad267e9c-bb27-4549-abd6-fae794d7fd8a
        secretKeyName: HOMEPAGE_VAR_UNIFI_APIKEY
      - bwSecretId: 3d4139a0-9ee9-4fe0-925e-fdd818434ff2
        secretKeyName: HOMEPAGE_VAR_NGINXPM_USER
      - bwSecretId: feec1ca2-5c2a-49db-8e30-3b7ebe215d0e
        secretKeyName: HOMEPAGE_VAR_NGINXPM_APIKEY
      - bwSecretId: c0ba2abc-1e1f-44fb-9de9-b39b01846d6d
        secretKeyName: HOMEPAGE_VAR_TRAEFIK_USER
      - bwSecretId: c0d58cd2-4c46-44ef-87fc-b39b0184903b
        secretKeyName: HOMEPAGE_VAR_TRAEFIK_PASSWORD
      - bwSecretId: f4683ad3-d2d9-48d8-a4d5-70e744321994
        secretKeyName: HOMEPAGE_VAR_PIHOLE_URL_ADMIN
      - bwSecretId: ca395b6c-5fb2-4a45-8215-b32bfd350662
        secretKeyName: HOMEPAGE_VAR_PIHOLE_URL
      - bwSecretId: 16e3e56c-2150-47b6-a0ca-ef4c1d05b3f6
        secretKeyName: HOMEPAGE_VAR_PIHOLE_APIKEY                                                                                     
      - bwSecretId: cf56b3de-12c2-4cc8-889f-69e50b591fee
        secretKeyName: HOMEPAGE_VAR_BACKUP_PIHOLE_URL_ADMIN
      - bwSecretId: 741f6b08-29f2-4936-9b35-6f653fb2a35f
        secretKeyName: HOMEPAGE_VAR_BACKUP_PIHOLE_URL
      - bwSecretId: db385b3a-62c3-4add-a85a-52d781dda6ea
        secretKeyName: HOMEPAGE_VAR_BACKUP_PIHOLE_APIKEY
      - bwSecretId: de6d703c-f2ec-44c1-9ffb-b3b900137583
        secretKeyName: HOMEPAGE_VAR_AUTHENTIK_URL
      - bwSecretId: ee722330-e5df-431a-b85d-b3b900122ec6
        secretKeyName: HOMEPAGE_VAR_AUTHENTIK_TOKEN
      - bwSecretId: 2eef1204-7987-4156-aae6-b3ef011a99e7
        secretKeyName: HOMEPAGE_VAR_ARGOCD_URL
      - bwSecretId: 952269a3-6b8e-4542-a49d-b3ef011adba0
        secretKeyName: HOMEPAGE_VAR_ARGOCD_TOKEN
      - bwSecretId: 6f144199-74e6-4c60-a618-2c4f7c0bc72c
        secretKeyName: HOMEPAGE_VAR_PLEX_URL
      - bwSecretId: 50ca6ac9-b20b-48cf-a2e9-5d92f36b485a
        secretKeyName: HOMEPAGE_VAR_PLEX_APIKEY
      - bwSecretId: 1a5d95c3-7e3a-44b6-ba45-2640a514e174
        secretKeyName: HOMEPAGE_VAR_SEERR_URL
      - bwSecretId: 52299f6b-f95f-4ca0-95a3-69575a4456dd
        secretKeyName: HOMEPAGE_VAR_SEERR_APIKEY
      - bwSecretId: b22f5951-640a-4302-b9df-de4952bc4544
        secretKeyName: HOMEPAGE_VAR_QBIT_USER
      - bwSecretId: 13d4a26b-8e6b-4194-8130-cdf190659c79
        secretKeyName: HOMEPAGE_VAR_QBIT_APIKEY
      - bwSecretId: 12e326e0-7972-4517-9faf-250efabfb331
        secretKeyName: HOMEPAGE_VAR_PRWLR_APIKEY
      - bwSecretId: 3c712c9c-620d-4aa7-ab74-ae0ab4778390
        secretKeyName: HOMEPAGE_VAR_RDR_APIKEY
      - bwSecretId: 134c5427-488c-4373-993f-44b286494c1f
        secretKeyName: HOMEPAGE_VAR_SNR_APIKEY
      - bwSecretId: 62f1bce6-5be8-42f7-aaa9-7fda9e498506
        secretKeyName: HOMEPAGE_VAR_LOCATION
      - bwSecretId: 10d217f9-b30f-4ab9-b73c-651ffb1e9d59
        secretKeyName: HOMEPAGE_VAR_LAT
      - bwSecretId: 73d14a75-ced2-4340-804a-10af8aebe66f
        secretKeyName: HOMEPAGE_VAR_LON
      - bwSecretId: bfe6a6c9-2564-483a-a68b-2934ded3e4a9
        secretKeyName: HOMEPAGE_VAR_TIMEZ                                                                                                       
  authToken:
    secretName: bw-auth-token
    secretKey: token