# Ensure to FIRST create K8s secret to authenticate with Bitwarden Secrets Manager
# read -s TOKEN (enter secret in shell not recorded)
# kubectl create secret generic bw-auth-token -n <YOUR_NAMESPACE> --from-literal=token="$TOKEN"

apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: bitwardensecret-kometa
  namespace: kometa 
  labels:
      app.kubernetes.io/name: bitwardensecret
      app.kubernetes.io/instance: bitwardensecret-kometa 
      app.kubernetes.io/part-of: sm-operator
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/created-by: sm-operator
spec:
  organizationId: "" # Fill this out using bw cli
  secretName: bw-kometa-secret 
  onlyMappedSecrets: true # default is true
  map:
      - bwSecretId: # Fill this out from BWS
        secretKeyName: KOMETA_PLEXURL
      - bwSecretId: # Fill this out from BWS
        secretKeyName: KOMETA_PLEXTOKEN
      - bwSecretId: # Fill this out from BWS
        secretKeyName: KOMETA_TMDBKEY
  authToken:
    secretName: bw-auth-token
    secretKey: token