# Ensure to FIRST create K8s secret to authenticate with Bitwarden Secrets Manager
# read -s TOKEN (enter secret in shell not recorded)
# kubectl create secret generic bw-auth-token -n <YOUR_NAMESPACE> --from-literal=token="$TOKEN"

apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: bitwardensecret-sample # Replace sample with your specified app
  namespace: default # Replace sample with your specified app namespace
  labels:
      app.kubernetes.io/name: bitwardensecret
      app.kubernetes.io/instance: bitwardensecret-sample # Replace sample with your specified app
      app.kubernetes.io/part-of: sm-operator
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/created-by: sm-operator
spec:
  organizationId: "a08a8157-129e-4002-bab4-b118014ca9c7" # Find you organization Id using Bitwarden CLI
  secretName: bw-sample-secret # Replace sample with your specified app
  onlyMappedSecrets: true # default is true
  map:
      - bwSecretId: 6c230265-d472-45f7-b763-b11b01023ca6 # Replace with BW Secret Id
        secretKeyName: APP_USERNAME-Secret-1# Replace with expected secret name that app requires
      - bwSecretId: d132a5ed-12bd-49af-9b74-b11b01025d58 # Replace with BW Secret Id
        secretKeyName: APP_API_KEY-Secret-2 # Replace with expected secret name that app requires                                                                                                
  authToken:
    secretName: bw-auth-token
    secretKey: token