apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media-pv
spec:
  capacity:
    storage: 10Ti             # ← adjust to your NAS share size
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 10.28.28.8       # ← your NAS IP
    path: /volume1/Vault/Media      # ← your NFS export path

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-pvc
  namespace: plex
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  volumeName: plex-media-pv
  resources:
    requests:
      storage: 10Ti