apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: longhorn-httproute
  namespace: longhorn-system
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
  hostnames:
    - longhorn.zeroenet.cloud
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
      - type: ExtensionRef
        extensionRef:  # Headers Middleware Definition
          group: traefik.io
          kind: Middleware
          name: secure-headers
      - type: ExtensionRef 
        extensionRef: # IP AllowList Middleware Definition
          group: traefik.io
          kind: Middleware
          name: admin-ip-allowlist
      - type: ExtensionRef
        extensionRef:
          group: traefik.io
          kind: Middleware
          name: dashboard-auth
      backendRefs:
        - name: longhorn-frontend
          port: 80