apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: peanut-claim0
  name: peanut-claim0
  namespace: peanut
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi
