apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -v convert
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: peanut
  name: peanut-lb
  namespace: peanut
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: peanut
