apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: metube-claim0
  name: metube-claim0
  namespace: metube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
