apiVersion: v1
kind: Pod
metadata:
  name: longhorn-pod-test
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh","-c","echo hello > /data/ok.txt && sleep 3600"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: test-longhorn-pvc