# Ensure to FIRST create K8s secret to authenticate with Bitwarden Secrets Manager
# read -s TOKEN (enter secret in shell not recorded)
# kubectl create secret generic bw-auth-token -n <YOUR_NAMESPACE> --from-literal=token="$TOKEN"

apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: bitwardensecret-open-webui
  namespace: kubeai
  labels:
      app.kubernetes.io/name: bitwardensecret
      app.kubernetes.io/instance: bitwardensecret-open-webui
      app.kubernetes.io/part-of: sm-operator
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/created-by: sm-operator
spec:
  organizationId: "577e1b7a-7f02-46a9-8af6-b31301796aa2"
  secretName: bw-open-webui-secret
  onlyMappedSecrets: true # default is true
  map:
      - bwSecretId: 1c994461-5df8-413b-abf7-b40b01328ae4
        secretKeyName: client-id
      - bwSecretId:  aa071c4c-f7e4-4578-9cb2-b40b0132b43b
        secretKeyName: client-secret                                                                                            
  authToken:
    secretName: bw-auth-token
    secretKey: token