# Ensure to FIRST create K8s secret to authenticate with Bitwarden Secrets Manager
# read -s TOKEN (enter secret in shell not recorded)
# kubectl create secret generic bw-auth-token -n <YOUR_NAMESPACE> --from-literal=token="$TOKEN"

apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: bitwardensecret-lubelogger 
  namespace: lubelogger
  labels:
      app.kubernetes.io/name: bitwardensecret
      app.kubernetes.io/instance: bitwardensecret-lubelogger 
      app.kubernetes.io/part-of: sm-operator
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/created-by: sm-operator
spec:
  organizationId: ""
  secretName: "bw-lubelogger-mail" 
  onlyMappedSecrets: true # default is true
  map:
      - bwSecretId: 
        secretKeyName: MailConfig__EmailServer
      - bwSecretId: 
        secretKeyName: MailConfig__EmailFrom
      - bwSecretId: 
        secretKeyName: MailConfig__Port
      - bwSecretId: 
        secretKeyName: MailConfig__Username
      - bwSecretId: 
        secretKeyName: MailConfig__Password
  authToken:
    secretName: bw-auth-token
    secretKey: token